name: Cypress Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run Cypress tests
        uses: cypress-io/github-action@v7
        with:
          command: npm run test:report

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: cypress-report
          path: reports/mochawesome/html
          if-no-files-found: warn

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
